pim/core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'auth.views.logged_in'),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^main/$', 'common.views.index', name='index'),
    url(r'^', include('django.contrib.staticfiles.urls')),
)

urlpatterns += staticfiles_urlpatterns()

pim/apps/common/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin
import consts as CONST


#class Living_situation(models.Model):
#    """
#    暮らし状況
#    """
#    def __unicode__(self):
#        return self.living_situation
    # 暮らし状況
#    living_situation = models.CharField(max_length=200)

#    def encode(self):
#        return {
#                'living_situation': self.living_situation,
#                }

#class Type(models.Model):
#    """
#    性格
#    """
#    def __unicode__(self):
#        return self.type
#    # 性格
#    type = models.CharField(max_length=200)

#    def encode(self):
#        return {
#                'type': self.type,
#                }

#class Level(models.Model):
#    """
#    レベル
#    """
#    def __unicode__(self):
#        return self.level_description
#    # レベル説明
#    level_description = models.CharField(max_length=50)

#    def encode(self):
#        return {
#                'level_description': self.level_description,
#                }

class Target(models.Model):
    """
    ターゲット情報モデル
    """
    def __unicode__(self):
        return self.name
    # 名前（漢字）
    name = models.CharField(max_length=200)
    # よみかた）
    reading = models.CharField(max_length=200)
    # 呼び名
    nick_name = models.CharField(max_length=200, blank=True)
    # 難易度
    difficulty = models.CharField(max_length=200, blank=True, null=True, choices=CONST.DIFFICULTY_CHOICES)
    #レベル
    level = models.IntegerField(choices=CONST.LEVEL_CHOICES)
    # 接触の目的
    purpose = models.CharField(max_length=50)
    # 会った日
    met_date = models.DateField()
    # 会った場所
    met_place = models.CharField(max_length=50, blank=True)
    # 会ったシチュエーション
    met_situation = models.CharField(max_length=200, blank=True)
    # 誕生日
    birthday = models.DateField(blank=True, null=True)
    # 電話番号
    phone_number = models.CharField(max_length=11, blank=True, null=True)
    # メールアドレス
    mail = models.CharField(max_length=200, blank=True)
    # 住所
    address = models.CharField(max_length=200, blank=True)
    # 職業
    occupation = models.CharField(max_length=200, blank=True)
    # 会社
    company = models.CharField(max_length=200, blank=True)
    # 趣味
    hobby = models.CharField(max_length=200, blank=True)
    # 出身地
    birth_place = models.CharField(max_length=200, blank=True)
    # ひとり暮らし:1, 実家:2, ルームシェア:3
    living_situation = models.CharField(max_length=200, blank=True, null=True, choices=CONST.LIVING_SITUATION_CHOICES)
    # 備考
    remarks = models.TextField(blank=True)
    # 性格1
    type_1 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 性格2
    type_2 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 性格3
    type_3 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 担当者ありフラグ
    taken_flg = models.BooleanField(default=False)
    # 終了フラグ
    done_flg = models.BooleanField(default=False)
    # ターゲット画像
    target_photo = models.ImageField(upload_to='targetPhoto/', null=True, blank=True)

    def encode(self):
        return {
                'name': self.name,
                'reading': self.reading,
                'difficulty': self.difficulty,
                'level': self.level,
                'purpose': self.purpose,
                'met_date': self.met_date,
                'met_place': self.met_place,
                'met_situation': self.met_situation,
                'birthday': self.birthday,
                'phone_number': self.phone_number,
                'mail': self.mail,
                'address': self.address,
                'occupation': self.occupation,
                'company': self.company,
                'hobby': self.hobby,
                'birth_place': self.birth_place,
                'living_situation': self.living_situation,
                'remarks': self.remarks,
                'type_1': self.type_1,
                'type_2': self.type_2,
                'type_3': self.type_3,
                'done_flg': self.done_flg,
                }

class Introduce(models.Model):
    """
    紹介者管理
    """
    def __unicode__(self):
        return self.introduced_by
    #紹介された人
    target = models.ForeignKey(Target, related_name='target')
    #紹介者
    introduced_by = models.ForeignKey(Target, related_name='introduced_by')

    def encode(self):
        return {
                'target': self.target.encode(),
                'introduced_by': self.introduced_by.encode(),
                }

class Target_relationship(models.Model):
    """
    ターゲット同士の関係性
    """
    def __unicode__(self):
        return self.relationship
    #ターゲット1
    target1 = models.ForeignKey(Target, related_name='target1')
    #ターゲット2
    target2 = models.ForeignKey(Target, related_name='target2')
    #関係性
    relationship = models.CharField(max_length=200)

    def encode(self):
        return {
                'target1': self.target1.encode(),
                'target2': self.target2.encode(),
                'relationship': self.relationship,
                }

class Team(models.Model):
    """
    チームモデル
    """
    def __unicode__(self):
        return self.name
    # チーム名
    name = models.CharField(max_length=200)
    # メンバー上限
    team_size = models.IntegerField(default=5)

    def encode(self):
        return {
                'name': self.name,
                }

class CustomUserManager(models.Manager):
    def create_user(self, username, email):
        return self.model._default_manager.create(username=username)

class User (models.Model):
    """
    ユーザモデル
    """
    def __unicode__(self):
        return self.username
    # ユーザID
    username = models.CharField(max_length=20, primary_key=True)
    # 名前（漢字）
    name = models.CharField(max_length=200, blank=True, verbose_name='名前(漢字)')
    # 名前（ひらがな）
    name_hiragana = models.CharField(max_length=200, blank=True, verbose_name='名前(ひらがな)')
    # 名前（英語）
    name_en = models.CharField(max_length=200, blank=True, verbose_name='名前(英語)')
    # チーム
    team = models.ForeignKey(Team, blank=True, null=True, verbose_name='チーム')
    # 誕生日
    birthday = models.DateField(blank=True, null=True, verbose_name='誕生日')
    # 出身地
    birth_place = models.CharField(max_length=200, blank=True, verbose_name='出身地')
    # 対象性格1
    target_type_1 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格1')
    # 対象性格2
    target_type_2 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格2')
    # 対象性格3
    target_type_3 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格3')
    # email
    email = models.CharField(max_length=200, verbose_name='Email')
    # プロファイル画像
    profile_photo = models.URLField(max_length=200, blank=True)
    # is_active
    is_active  = models.BooleanField(default=True)
    # last login
    last_login = models.DateTimeField(blank=True, null=True)
    #チーム管理者フラグ
#    team_admin_flg = models.BooleanField(default=False)
    # ユーザの状態。0=アカウント停止、1=仮登録、2=無料会員、3=有料会員
    status = models.IntegerField(default=1)

    objects = CustomUserManager();

    def is_authenticated(self):
        return True

    def encode(self):
        return {
                'username': self.username,
                'name': self.name,
                'name_hiragana': self.name_hiragana,
                'name_en': self.name_en,
                'team': self.team,
                'birthday': self.birthday,
                'birth_place': self.birth_place,
                'target_type_1': self.target_type_1,
                'target_type_2': self.target_type_2,
                'target_type_3': self.target_type_3,
                'profile_photo': self.profile_photo,
                }

class Membership(models.Model):
    """
    チームとメンバーの関係の中間モデル
    """
    def __unicode__(self):
        return self.team.name

    # チーム
    team = models.ForeignKey(Team)
    # ユーザ
    user = models.ForeignKey(User)
    # チーム管理者フラグ
    team_admin_flg = models.BooleanField(default=False)

    def encode(self):
        return {
                'team': self.team.encode(),
                'user': self.ruser.encode(),
                'team_admin_flg': self.team_admin_flg.encode(),
                }


class Invitation(models.Model):
    """
    チーム招待中間モデル
    """
    def __unicode__(self):
        return self.team

    # チーム
    team = models.ForeignKey(Team)
    # 被招待者
    invited_user = models.ForeignKey(User, related_name="invited_user")
    # 招待者
    invited_by = models.ForeignKey(User, related_name="invited_by")
    # 管理者承認フラグ
    approve_by_admin_flg = models.BooleanField(default=False)
    # 被招待者承認フラグ
    approve_by_user_flg = models.BooleanField(default=False)

#class Progress(models.Model):
#    """
#    進捗マスタ
#    """
#    def __unicode__(self):
#        return self.progress_name
#    #進捗名
#    progress_name = models.CharField(max_length=50)

#    def encode(self):
#        return {
#                'progress_name': self.progress_name,
#                }

class Progress_management(models.Model):
    """
    担当者定義モデル
    """
    def __unicode__(self):
        return unicode(self.progress)
    # 顧客
    target = models.ForeignKey(Target, verbose_name='顧客')
    # 担当者
    responsible_by = models.ForeignKey(User, verbose_name='担当者')
    # 関係性
    relationship = models.CharField(max_length=200, verbose_name='関係性')
    # 進捗状況
    progress = models.CharField(max_length=200, choices=CONST.PROGRESS_CHOICES, verbose_name='進捗状況')
    # 備考
    remarks = models.TextField(blank=True, verbose_name='備考')
    # 登録日時
    registered_at = models.DateTimeField(auto_now_add=True, verbose_name='登録日時')

    def encode(self):
        return {
                'target': self.target.encode(),
                'responsible_by': self.responsible_by.encode(),
                'relationship': self.relationship,
                'progress': self.progress,

pim/apps/team/models.py
# -*- coding: utf-8 -*-

# Create your models here.
import services as SERVICES

class Team_Members(object):
    """
    チーム画面のリストに表示する1チームに対するモデル
    """
    def __unicode__(self):
        return self.username

    def __init__(self, team, members):
        self.team = team
        self.members = members
        self.team_admin = SERVICES.selectTeamAdmin(team)

pim/apps/team/forms.py
'''
Created on 2014/07/23

@author: h-nagata
'''
from django import forms

class TeamAddForm(forms.Form):
    name = forms.CharField(max_length=50)

    def __init__(self, *args, **kwargs):
        super(TeamAddForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'

class TeamInviteForm(forms.Form):
    team_id = forms.CharField(max_length=50, widget=forms.HiddenInput())
    user_id = forms.CharField(max_length=200)

    def __init__(self, *args, **kwargs):
        super(TeamInviteForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].widget.attrs['class'] = 'form-control'

pim/apps/team/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.core.context_processors import csrf
import configs as CONFIG
import settings as SETTING
import services as SERVICES
import models as TEAM_MODELS
import forms as FORMS
import messages as MSGS
import logging

logger = logging.getLogger('app')

# Create your views here.
def index(request):
    logger.info('チーム画面開始')
    c = {}

    return show(request, c)

def add(request):
    """
    チーム登録
    """
    logger.info('チーム登録')

    if request.method == 'POST':
        teamAddForm = FORMS.TeamAddForm(request.POST)
        result = SERVICES.addNewTeam(teamAddForm, request.user)

        if not result == 'success':
            fail_form = FORMS.TeamAddForm(request.POST)
            c = {'teamAddForm':fail_form}
            c.update({'form_message':MSGS.ADD_FAIL})
            return show(request, c)

    c = {'form_message': MSGS.ADD_SUCCESS}
    return show(request, c)

def invite(request):
    """
    チーム招待
    """
    logger.info('チーム招待')
    c = {}

    if request.method == 'POST':
        team_invite_form = FORMS.TeamInviteForm(request.POST)
        result = SERVICES.inviteUser(team_invite_form, request.user)

        if not result == 'success':
            fail_form = FORMS.TeamInviteForm(request.POST)
            c = {'teamInviteForm':fail_form}
            c.update({'form_message':MSGS.INVITE_FAIL})
            return show(request, c)

    c = {'form_message': MSGS.INVITE_SUCCESS}

    return show(request, c)

def acceptMember(request):
    """
    チームに招待されたユーザを管理者が承認する
    """
    logger.info('チーム招待管理者承認')
    c = {}
    if request.method == "POST":
        invited_username = request.POST["invited_username"]

    print invited_username
    if invited_username:
        invited_user = SERVICES.selectUserById(invited_username)
        if invited_user is None:
            c.update({'form_message':MSGS.INVITE_ACCEPT_FAIL})
            return show(request, c)
    else:
        c.update({'form_message':MSGS.INVITE_ACCEPT_FAIL})
        return show(request, c)

    result = SERVICES.acceptMember(invited_user, SERVICES.selectTeamsByUser(request.user)[0])

    if result == 'success':
        c.update({'form_message': MSGS.INVITE_ACCEPT_SUCCESS})
    else:
        c.update({'form_message':MSGS.INVITE_ACCEPT_FAIL})

    return show(request, c)

def acceptTeam(request):
    """
    チームに招待された被招待者が承認する
    """
    logger.info('チーム招待被招待者承認')
    c = {}
    if request.method == "POST":
        team_id = request.POST["team_id"]

    if team_id:
        team = SERVICES.selectTeamById(team_id)
        if team is None:
            return index(request)
    else:
        return index(request)

    result = SERVICES.acceptTeamInvited(request.user, team)

    if result == 'success':
        c.update({'form_message': MSGS.INVITE_ACCEPT_SUCCESS})
    else:
        c.update({'form_message':MSGS.INVITE_ACCEPT_FAIL})


    return show(request, c)

def deleteMember(request):
    """
    チームからメンバーを削除する
    """
    logger.info('チームメンバ^－削除')
    c = {}

    if request.method == "POST":
        username = request.POST["object_id"]
        team_id = request.POST["delete_from_id"]

    user = SERVICES.selectUserById(username)
    team = SERVICES.selectTeamById(team_id)

    if user and team:
        result = SERVICES.deleteMember(user, team)

    if result == 'success':
        c.update({'list_form_message': MSGS.DELETE_MEMBER_SUCCESS})
    else:
        c.update({'list_form_message':MSGS.DELETE_MEMBER_FAIL})


    return show(request, c)

def deleteTeam(request):
    """
    チームを削除する
    """
    logger.info('チーム削除')
    c = {}

    if request.method == "POST":
        team_id = request.POST["object_id"]

    team = SERVICES.selectTeamById(team_id)

    if team:
        result = SERVICES.deleteTeam(team)

    if result == 'success':
        c.update({'team_delete_message': MSGS.DELETE_MEMBER_SUCCESS})
    else:
        c.update({'team_delete_message':MSGS.DELETE_MEMBER_FAIL})

    return show(request, c)

def show(request, c):
    """
    チームメンバー一覧画面インデックス
    最初に必ず通る
    """
    logger.info('チームメンバーリスト画面開始')

    team_list = SERVICES.selectTeamsByUser(request.user)

    # 一覧表示用チームメンバーリスト作成
    team_members_list = generateTeamMembersList(team_list)
    c.update({'team_members_list':team_members_list})

    # テンプレートに渡すフォームを作成する
    forms = generateForms(team_list, request.user)
    c.update(forms)

    # 承認待ちユーザリストを作成する
    waiting_user_list = SERVICES.selectWaitingUserList(team_list)
    c.update({'waiting_user_list':waiting_user_list})

    main_url = CONFIG.TOP_URL
    page_title = CONFIG.TEAM_PAGE_TITLE_URL
    main_content = CONFIG.TEAM_MAIN_URL
    sub_content = CONFIG.TEAM_SUB_URL

    url_dict = {'main_url':main_url,
                'page_title':page_title,
                'main_content':main_content,
                'sub_content':sub_content}
    c.update({'master_user_name':SETTING.MASTER_USER_NAME})
    c.update(csrf(request))
    c.update({'html_title':CONFIG.TEAM_HTML_TITLE})
    c.update(url_dict)
    c.update(CONFIG.ACTION_DICT)
    return render(request, 'common/main.html', c)

def generateTeamMembersList(team_list):
    """
    表示用チームメンバーリストを作成する
    """
    team_members_list = []
    for team in team_list:
        users = SERVICES.selectUsersByTeam(team)
        team_members_list.append(TEAM_MODELS.Team_Members(team, users))

    return team_members_list

def generateForms(team_list, user):
    """
    チームに所属しているか判定する。所属していない場合、チーム登録フォームを渡す
    所属している場合、招待フォームを渡す
    return forms{}
    """
    forms = {}
    if team_list:
        forms.update({'teamInviteForm':FORMS.TeamInviteForm(initial={'team_id':team_list[0].id})})
        forms.update({'has_team':True})
    else:
        forms.update({'teamAddForm':FORMS.TeamAddForm()})

    # 承認待ちユーザ管理者用
    if team_list:
        if SERVICES.isTeamAdmin(team_list[0], user):
            admin_approval_waiting_user_list = SERVICES.selectAdminApprovalWaitingUserList(team_list[0])
            forms.update({'admin_approval_waiting_user_list':admin_approval_waiting_user_list})

    # 承認待ちチーム被招待者用
    inviting_team_list = SERVICES.selectInvitingTeamList(user)
    forms.update({'inviting_team_list':inviting_team_list})

    return forms

pim/templates/team/main_content.html
    <div id="main_content">
      <span style="color:red;">{{ team_delete_message }}</span>
      {% for team_members in team_members_list %}
        <table>
          <tbody>
            {% if list_form_message %}
             <tr>
              <td>
                <span style="color:red;">{{list_form_message}}</span>
              </td>
             </tr>
            {% endif %}
            <tr>
              <th>
                チーム名：{{team_members.team.name}}
                 &nbsp;
                 {% if team_members.team_admin == user  %}
                   <span style="font-size:8px">
                     <a href="javascript:void(0)" onClick="deleteObject('{{team_members.team.id}}', '', '{{ACTION_TEAM_DELETE_TEAM}}');return false;">
                       チーム削除
                     </a>
                   </span>
                 {% endif %}
              </th>
            </tr>

          </tbody>
        </table>
        <table class="table table-hover">
          <tbody>
          <form id="list_form" method="post" action="{{main_url}}">
          {% csrf_token %}
            {% for members in team_members.members %}
            <tr>
              <td class="col-md-2">
                <img src="{{ members.profile_photo|cut:"_normal" }}" width="100%">
              </td>
              <td class="col-md-10">
                <table style="width:100%;">
                  <tr>
                    <td class="col-md-12" colspan="4">
                      {{members.username}}
                    </td>
                    <td>
                    {% if team_members.team_admin == members %}
                     <img src="{{STATIC_URL}}images/admin.png" width="20px">
                    {% endif %}
                    {% if team_members.team_admin == user and members != user %}
                      <a href="javascript:void(0)" onClick="deleteObject('{{members.username}}', '{{team_members.team.id}}', '{{ACTION_TEAM_DELETE_MEMBER}}');return false;">
                        <i class="glyphicon glyphicon-remove"></i>
                      </a>
                    {% endif %}
                    </td>
                  <tr>
                  <tr>
                    <th class="col-md-2">
                      出身:
                    </th>
                    <td class="col-md-5">
                      {% if members.birth_place  %}
                      {{ members.birth_place }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                    <th class="col-md-2">
                      誕生日:
                    </th>
                    <td class="col-md-5">
                      {% if members.birthday  %}
                      {{ members.birthday }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      対象:
                    </th>
                    <td class="col-md-10" colspan="3">
                      {% if members.target_type_1  %}
                      {{ members.get_target_type_1_display }}
                      {% endif %}
                      {% if members.target_type_2  %}
                      {{ members.get_target_type_2_display }}
                      {% endif %}
                      {% if members.target_type_3  %}
                      {{ members.get_target_type_3_display }}
                      {% endif %}
                    </td>
                  </tr>

                </table>
              </td>
            </tr>
            {% endfor %}
            </form>

          </tbody>
        </table>

      {% endfor %}
    </div>

pim/templates/team/page_title.html
<div class="page_title">&nbsp;Team Information</div>

pim/templates/team/sub_content.html
    <div id="sub_content">
        {{form_message}}

        <!-- 新規チーム追加フォーム -->
        {% if teamAddForm %}
          <form method="POST" action="{{main_url}}">
          {%csrf_token%}

          <div class="fieldWrapper form-group">
            {{ teamAddForm.name.errors }}
            <label for="id_name">チーム名:</label>
            {{ teamAddForm.name }}
          </div>
          <input type="hidden" name="action" value="{{ACTION_TEAM_ADD}}">
          <button id="id_team_add_submit" type="submit" class="btn btn-default">作成</button>
        </form>
        {% endif %}
        <!-- ここまで -->

        <!-- メンバー招待フォーム -->
        {% if has_team %}
          <form method="POST" action="{{main_url}}">
          {%csrf_token%}

          <div class="fieldWrapper form-group">
            {{ teamInviteForm.user_id.errors }}
            <label for="id_user_id">ユーザ:</label>
            {{ teamInviteForm.user_id }}
          </div>

          {% for hidden in teamInviteForm.hidden_fields %}
          {{ hidden }}
          {% endfor %}



          <input type="hidden" name="action" value="{{ACTION_TEAM_INVITE}}">
          <button id="id_team_invite_submit" type="submit" class="btn btn-default">招待する</button>
        </form>
        {% endif %}
        <!-- ここまで -->

        <br>

        <!-- 承認待ちユーザ管理者用 -->
        {% if admin_approval_waiting_user_list %}
          管理者承認待ちユーザ
          <form id="admin_approval_form" method="POST" action="{{main_url}}">
          {%csrf_token%}
          {% for admin_approval_waiting_user in admin_approval_waiting_user_list %}
          ・{{ admin_approval_waiting_user.username }} &nbsp;<a href="#" onclick="acceptMember('{{ admin_approval_waiting_user.username }}', '{{ ACTION_TEAM_INVITE_ACCEPT_USER }}');">承認</a><br>
          {%  endfor %}
          </form>
        {% endif %}
        <!-- ここまで -->

        <!-- 承認待ちチーム -->
          {% if inviting_team_list %}
          承認待ちチーム
          <form id="invited_user_approval_form" method="POST" action="{{main_url}}">
          {%csrf_token%}
          {% for inviting_team in inviting_team_list %}
          ・{{ inviting_team.name }} &nbsp;<a href="#" onclick="acceptTeam('{{ inviting_team.id }}', '{{ ACTION_TEAM_INVITE_ACCEPT_TEAM }}');">承認</a><br>
          {% endfor %}
          </form>
          {% endif %}
        <!-- ここまで -->

        <!-- 承認待ちユーザ表示 -->
        {% if waiting_user_list %}
        <br><br>
        承認待ちユーザ<br>
          {% for waiting_user in waiting_user_list %}
          ・{{ waiting_user.username }}<br>
          {% endfor %}
        {% endif %}
        <!-- ここまで -->

    </div>