pim/core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'auth.views.logged_in'),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^main/$', 'common.views.index', name='index'),
    url(r'^', include('django.contrib.staticfiles.urls')),
)

urlpatterns += staticfiles_urlpatterns()

pim/apps/common/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin
import consts as CONST


#class Living_situation(models.Model):
#    """
#    暮らし状況
#    """
#    def __unicode__(self):
#        return self.living_situation
    # 暮らし状況
#    living_situation = models.CharField(max_length=200)

#    def encode(self):
#        return {
#                'living_situation': self.living_situation,
#                }

#class Type(models.Model):
#    """
#    性格
#    """
#    def __unicode__(self):
#        return self.type
#    # 性格
#    type = models.CharField(max_length=200)

#    def encode(self):
#        return {
#                'type': self.type,
#                }

#class Level(models.Model):
#    """
#    レベル
#    """
#    def __unicode__(self):
#        return self.level_description
#    # レベル説明
#    level_description = models.CharField(max_length=50)

#    def encode(self):
#        return {
#                'level_description': self.level_description,
#                }

class Target(models.Model):
    """
    ターゲット情報モデル
    """
    def __unicode__(self):
        return self.name
    # 名前（漢字）
    name = models.CharField(max_length=200)
    # よみかた）
    reading = models.CharField(max_length=200)
    # 呼び名
    nick_name = models.CharField(max_length=200, blank=True)
    # 難易度
    difficulty = models.CharField(max_length=200, blank=True, null=True, choices=CONST.DIFFICULTY_CHOICES)
    #レベル
    level = models.IntegerField(choices=CONST.LEVEL_CHOICES)
    # 接触の目的
    purpose = models.CharField(max_length=50)
    # 会った日
    met_date = models.DateField()
    # 会った場所
    met_place = models.CharField(max_length=50, blank=True)
    # 会ったシチュエーション
    met_situation = models.CharField(max_length=200, blank=True)
    # 誕生日
    birthday = models.DateField(blank=True, null=True)
    # 電話番号
    phone_number = models.CharField(max_length=11, blank=True, null=True)
    # メールアドレス
    mail = models.CharField(max_length=200, blank=True)
    # 住所
    address = models.CharField(max_length=200, blank=True)
    # 職業
    occupation = models.CharField(max_length=200, blank=True)
    # 会社
    company = models.CharField(max_length=200, blank=True)
    # 趣味
    hobby = models.CharField(max_length=200, blank=True)
    # 出身地
    birth_place = models.CharField(max_length=200, blank=True)
    # ひとり暮らし:1, 実家:2, ルームシェア:3
    living_situation = models.CharField(max_length=200, blank=True, null=True, choices=CONST.LIVING_SITUATION_CHOICES)
    # 備考
    remarks = models.TextField(blank=True)
    # 性格1
    type_1 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 性格2
    type_2 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 性格3
    type_3 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 担当者ありフラグ
    taken_flg = models.BooleanField(default=False)
    # 終了フラグ
    done_flg = models.BooleanField(default=False)
    # ターゲット画像
    target_photo = models.ImageField(upload_to='targetPhoto/', null=True, blank=True)

    def encode(self):
        return {
                'name': self.name,
                'reading': self.reading,
                'difficulty': self.difficulty,
                'level': self.level,
                'purpose': self.purpose,
                'met_date': self.met_date,
                'met_place': self.met_place,
                'met_situation': self.met_situation,
                'birthday': self.birthday,
                'phone_number': self.phone_number,
                'mail': self.mail,
                'address': self.address,
                'occupation': self.occupation,
                'company': self.company,
                'hobby': self.hobby,
                'birth_place': self.birth_place,
                'living_situation': self.living_situation,
                'remarks': self.remarks,
                'type_1': self.type_1,
                'type_2': self.type_2,
                'type_3': self.type_3,
                'done_flg': self.done_flg,
                }

class Introduce(models.Model):
    """
    紹介者管理
    """
    def __unicode__(self):
        return self.introduced_by
    #紹介された人
    target = models.ForeignKey(Target, related_name='target')
    #紹介者
    introduced_by = models.ForeignKey(Target, related_name='introduced_by')

    def encode(self):
        return {
                'target': self.target.encode(),
                'introduced_by': self.introduced_by.encode(),
                }

class Target_relationship(models.Model):
    """
    ターゲット同士の関係性
    """
    def __unicode__(self):
        return self.relationship
    #ターゲット1
    target1 = models.ForeignKey(Target, related_name='target1')
    #ターゲット2
    target2 = models.ForeignKey(Target, related_name='target2')
    #関係性
    relationship = models.CharField(max_length=200)

    def encode(self):
        return {
                'target1': self.target1.encode(),
                'target2': self.target2.encode(),
                'relationship': self.relationship,
                }

class Team(models.Model):
    """
    チームモデル
    """
    def __unicode__(self):
        return self.name
    # チーム名
    name = models.CharField(max_length=200)
    # メンバー上限
    team_size = models.IntegerField(default=5)

    def encode(self):
        return {
                'name': self.name,
                }

class CustomUserManager(models.Manager):
    def create_user(self, username, email):
        return self.model._default_manager.create(username=username)

class User (models.Model):
    """
    ユーザモデル
    """
    def __unicode__(self):
        return self.username
    # ユーザID
    username = models.CharField(max_length=20, primary_key=True)
    # 名前（漢字）
    name = models.CharField(max_length=200, blank=True, verbose_name='名前(漢字)')
    # 名前（ひらがな）
    name_hiragana = models.CharField(max_length=200, blank=True, verbose_name='名前(ひらがな)')
    # 名前（英語）
    name_en = models.CharField(max_length=200, blank=True, verbose_name='名前(英語)')
    # チーム
    team = models.ForeignKey(Team, blank=True, null=True, verbose_name='チーム')
    # 誕生日
    birthday = models.DateField(blank=True, null=True, verbose_name='誕生日')
    # 出身地
    birth_place = models.CharField(max_length=200, blank=True, verbose_name='出身地')
    # 対象性格1
    target_type_1 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格1')
    # 対象性格2
    target_type_2 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格2')
    # 対象性格3
    target_type_3 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格3')
    # email
    email = models.CharField(max_length=200, verbose_name='Email')
    # プロファイル画像
    profile_photo = models.URLField(max_length=200, blank=True)
    # is_active
    is_active  = models.BooleanField(default=True)
    # last login
    last_login = models.DateTimeField(blank=True, null=True)
    #チーム管理者フラグ
#    team_admin_flg = models.BooleanField(default=False)
    # ユーザの状態。0=アカウント停止、1=仮登録、2=無料会員、3=有料会員
    status = models.IntegerField(default=1)

    objects = CustomUserManager();

    def is_authenticated(self):
        return True

    def encode(self):
        return {
                'username': self.username,
                'name': self.name,
                'name_hiragana': self.name_hiragana,
                'name_en': self.name_en,
                'team': self.team,
                'birthday': self.birthday,
                'birth_place': self.birth_place,
                'target_type_1': self.target_type_1,
                'target_type_2': self.target_type_2,
                'target_type_3': self.target_type_3,
                'profile_photo': self.profile_photo,
                }

class Membership(models.Model):
    """
    チームとメンバーの関係の中間モデル
    """
    def __unicode__(self):
        return self.team.name

    # チーム
    team = models.ForeignKey(Team)
    # ユーザ
    user = models.ForeignKey(User)
    # チーム管理者フラグ
    team_admin_flg = models.BooleanField(default=False)

    def encode(self):
        return {
                'team': self.team.encode(),
                'user': self.ruser.encode(),
                'team_admin_flg': self.team_admin_flg.encode(),
                }


class Invitation(models.Model):
    """
    チーム招待中間モデル
    """
    def __unicode__(self):
        return self.team

    # チーム
    team = models.ForeignKey(Team)
    # 被招待者
    invited_user = models.ForeignKey(User, related_name="invited_user")
    # 招待者
    invited_by = models.ForeignKey(User, related_name="invited_by")
    # 管理者承認フラグ
    approve_by_admin_flg = models.BooleanField(default=False)
    # 被招待者承認フラグ
    approve_by_user_flg = models.BooleanField(default=False)

#class Progress(models.Model):
#    """
#    進捗マスタ
#    """
#    def __unicode__(self):
#        return self.progress_name
#    #進捗名
#    progress_name = models.CharField(max_length=50)

#    def encode(self):
#        return {
#                'progress_name': self.progress_name,
#                }

class Progress_management(models.Model):
    """
    担当者定義モデル
    """
    def __unicode__(self):
        return unicode(self.progress)
    # 顧客
    target = models.ForeignKey(Target, verbose_name='顧客')
    # 担当者
    responsible_by = models.ForeignKey(User, verbose_name='担当者')
    # 関係性
    relationship = models.CharField(max_length=200, verbose_name='関係性')
    # 進捗状況
    progress = models.CharField(max_length=200, choices=CONST.PROGRESS_CHOICES, verbose_name='進捗状況')
    # 備考
    remarks = models.TextField(blank=True, verbose_name='備考')
    # 登録日時
    registered_at = models.DateTimeField(auto_now_add=True, verbose_name='登録日時')

    def encode(self):
        return {
                'target': self.target.encode(),
                'responsible_by': self.responsible_by.encode(),
                'relationship': self.relationship,
                'progress': self.progress,

pim/apps/progress/forms.py
# -*- coding: utf-8 -*-
from django import forms
import common.models as MODELS
from django.forms.widgets import Textarea
#from common.models import Target_register
import services as SERVICES

class ProgressManagementForm(forms.ModelForm):

    select_target = forms.ChoiceField(choices=())

    class Meta:
        model = MODELS.Progress_management

        # 表示したいフィールド名だけを指定する。
        fields = ('select_target',  'relationship', 'progress', 'remarks')

        # remarksのname属性をtextareaに変更
        widgets = {
            'remarks': Textarea(attrs={'cols': 40, 'rows': 10}),
        }

    def __init__(self, user, *args, **kwargs):
        super(ProgressManagementForm, self).__init__(*args, **kwargs)

        # formの__init__を上書きして、ターゲットを表示するようにする
        # 表示ターゲット：自分が登録したターゲット、チームターゲット
        # リストから除外するターゲット：自分以外が担当しているターゲット
        if SERVICES.hasTeam(user):
            target_list = SERVICES.selectTeamTargetList(user)
            target_dict = []
            for target in target_list:
                if not SERVICES.targetTakenByOthers(target, user):
                    target_dict.append((target.id, target))
        else:
            target_dict = [(target_register.target.id, target_register.target)
                           for target_register
                           in MODELS.Target_register.objects.filter(user=user)]

        self.fields['select_target'] = forms.ChoiceField(choices=target_dict)
        self.fields['select_target'].label = '担当'
        self.fields['select_target'].widget.attrs['class'] = 'form-control'

        self.fields['relationship'].widget.attrs['class'] = 'form-control'
        self.fields['progress'].widget.attrs['class'] = 'form-control'
        self.fields['remarks'].widget.attrs['class'] = 'form-control'

pim/apps/progress/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.core.context_processors import csrf
import configs as CONFIG
import settings as SETTING
from progress.forms import ProgressManagementForm
import forms as FORMS
import services as SERVICES
import messages as MSGS
import logging
logger = logging.getLogger('app')

#
def index(request):

    logger.info('index')

    form = {'form':ProgressManagementForm(request.user)}
    c = {}
    c.update(form)
    return list_init(request, c)


def add(request):
    logger.info('add')

    if request.method == 'POST':
        result = SERVICES.addProgress(request.user, request.POST)
        if not result == 'success':
            fail_form = FORMS.ProgressManagementForm(request.user, request.POST)
            c = {'form':fail_form}
            c.update({'form_message':MSGS.ADD_FAIL})
            return list_init(request, c)
    c = {'form_message': MSGS.ADD_SUCCESS}
    c.update({'form':FORMS.ProgressManagementForm(request.user, )})
    return list_init(request, c)

def update(request):
    logger.info('update')

    if request.method == 'POST':
        result = SERVICES.updateProgress(request.user, request.POST)
        if not result == 'success':
            fail_form = FORMS.ProgressManagementForm(request.user, request.POST)
            c = {'form':fail_form}
            c.update({'form_message':MSGS.UPD_FAIL})
            return list_init(request, c)
    c = {'form_message': MSGS.UPD_SUCCESS}
    c.update({'form':FORMS.ProgressManagementForm(request.user, )})
    return list_init(request, c)

def search(request):
    logger.info('search')
    form = {'form':ProgressManagementForm(request.user)}
    c = {}
    c.update(form)

    if request.method == 'POST':
        key = request.POST['key']
        if key:
            # 担当者の進捗一覧を取得し、返却する
            user_progress_list = SERVICES.getUserProgressListByKey(request.user, key)
            c.update({'user_progress_list':user_progress_list})

            # 担当者の所属するチームの別メンバの進捗を取得し、返却する
            team_progress_lists = SERVICES.getTeamProgressList(request.user, key)
            c.update({'team_progress_lists':team_progress_lists})
            c.update({'key':key})
            return show(request, c)

    return list_init(request, c)

def list_init(request, c):
    # 担当者の進捗一覧を取得し、返却する
    user_progress_list = SERVICES.getUserProgressList(request.user)
    c.update({'user_progress_list':user_progress_list})

    # 担当者の所属するチームの別メンバの進捗を取得し、返却する
    team_progress_lists = SERVICES.getTeamProgressList(request.user)
    c.update({'team_progress_lists':team_progress_lists})

    return show(request, c)

def show(request, c):
    logger.info('show')
    main_url = CONFIG.TOP_URL
    page_title = CONFIG.PROGRESS_PAGE_TITLE_URL
    main_content = CONFIG.PROGRESS_MAIN_URL
    sub_content = CONFIG.PROGRESS_SUB_URL
    insert_button = CONFIG.INSERT_BUTTON
    search_action= CONFIG.ACTION_PROGRESS_SEARCH
#     form = {'form':ProgressManagementForm()}
    url_dict = {'main_url':main_url,
                'page_title':page_title,
                'main_content':main_content,
                'sub_content':sub_content,
                'insert_button':insert_button,
                'search_action':search_action}
    c.update({'master_user_name':SETTING.MASTER_USER_NAME})
    c.update(csrf(request))
    c.update({'html_title':CONFIG.PROGRESS_HTML_TITLE})
    c.update(url_dict)
    c.update(CONFIG.ACTION_DICT)
    return render(request, 'common/main.html', c)

pim/templates/progress/main_content.html
    <div id="main_content">
      <table class="table table-hover">
        <thead>
          <tr>
            <td class="col-md-3 col-sm-3"></td>
            <td class="col-md-9 col-sm-9">
                <table class="table-bordered">
                    <tr>
                      <td class="col-md-2 col-sm-2">progress</td>
                      <td class="col-md-3 col-sm-3">registered_at</td>
                      <td class="col-md-3 col-sm-3">relationship</td>
                      <td class="col-md-4 col-sm-4">remarks</td>
                      <td>edit</td>
                    </tr>
                </table>
            </td>
          </tr>
        </thead>

        <tbody>
        {% for user_progress in user_progress_list%}
              {% comment %}
                <!-- 前と顧客が変わったら印字する -->
              {% endcomment %}
              {% ifchanged user_progress.target.pk %}
                    {% if forloop.first %}
                    <tr>
                         <td class="col-md-3" valign="middle">
                    {% else %}
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td class="col-md-3" valign="middle">
                    {% endif %}
                              名前:{{ user_progress.target.name }}<br>
                              LV:{{ user_progress.target.level }}<br>
                              目的:{{ user_progress.target.purpose }}<br>
                        </td>
                <td class="col-md-9">
                    <table class="table-striped">
              {% endifchanged %}
                          <tr>
                              <td id="id_user_progress_id_{{ user_progress.id }}" style="display:none">{{ user_progress.id }}</td>
                              <td id="target_{{ user_progress.id }}" style="display:none">{{ user_progress.target.id }}</td>
                              <td class="col-md-2">{{ user_progress.get_progress_display }}</td>
                              <td id="progress_{{ user_progress.id }}" style="display:none">{{ user_progress.progress }}</td>
                              <td class="col-md-3">{{ user_progress.registered_at|date:"Y-m-d(D)" }}</td>
                              <td id="relationship_{{ user_progress.id }}" class="col-md-3">{{ user_progress.relationship }}</td>
                              <td id="remarks_{{ user_progress.id }}" class="col-md-4">{{ user_progress.remarks }}</td>
                              <td>
<!--                               <a href="javascript:void(0)" onClick="setSubContentForm('{{ user_progress.id }}');return false;"><i class="glyphicon glyphicon-pencil"></i></a>
 -->
                              <a href="#sub_content" onClick="setSubContentForm('{{ user_progress.id }}');return false;"><i class="glyphicon glyphicon-pencil"></i></a>
                              </td>
                          </tr>
              {% if forloop.last %}
                            </table>
                        </td>
                    </tr>
              {% endif %}
        {% endfor %}

        </tbody>
      </table>

        {% comment %}
            <!-- ↓ この下に担当者の所属するチームの別メンバの進捗を表示する ↓ -->
        {% endcomment %}

        {% for team_progress_list in team_progress_lists%}
      <table class="table table-hover">
           <tbody>
            {% for team_progress in team_progress_list%}
                  {% ifchanged team_progress.responsible_by %}
                        チームメンバ:{{ team_progress.responsible_by }} の進捗状況
                  {% endifchanged %}
                  {% comment %}
                    <!-- 前と顧客が変わったら印字する -->
                  {% endcomment %}
                  {% ifchanged team_progress.target.pk %}
                        {% if forloop.first %}
                        <tr>
                             <td class="col-md-2" valign="middle">
                        {% else %}
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-md-2" valign="middle">
                        {% endif %}
                                  名前:{{ team_progress.target.name }}<br>
                                  LV:{{ team_progress.target.level }}<br>
                                  目的:{{ team_progress.target.purpose }}<br>
                            </td>
                    <td class="col-md-10">
                        <table class="table-striped">
                  {% endifchanged %}
                              <tr>
                                  <td class="col-md-2">{{ team_progress.get_progress_display }}</td>
                                  <td class="col-md-3">{{ team_progress.registered_at|date:"Y-m-d(D)" }}</td>
                                  <td id="relationship_{{ team_progress.id }}" class="col-md-3">{{ team_progress.relationship }}</td>
                                  <td id="remarks_{{ team_progress.id }}" class="col-md-4">{{ team_progress.remarks|linebreaks }}</td>
                              </tr>
                  {% if forloop.last %}
                                </table>
                            </td>
                        </tr>
                  {% endif %}
            {% endfor %}

            </tbody>
           </table>
           <hr>
        {% endfor %}
    </div>

pim/templates/progress/page_title.html
<div class="page_title">&nbsp;Progress List</div>

pim/templates/progress/sub_content.html
    <div id="sub_content" class="white-popup mfp-hide">
        {{form_message}}
        <form method="POST" action="{{main_url}}">
        {%csrf_token%}
        <h4>進捗登録</h4>
        {{ form.as_p }}
        <input id="id_progress_action" type="hidden" name="action" value="{{ACTION_PROGRESS_ADD}}">
        <input type="hidden" name="responsible_by_id" value="{{ user.username }}">
        <input id="id_user_progress_id" type="hidden" name="user_progress_id" value="">
        <button id="id_submit_progress" type="submit" class="btn btn-default">登録</button>
        </form>
        <button class="btn btn-default" onclick="moveTo('progress_list');">キャンセル</button>

    </div>