pim/core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'auth.views.logged_in'),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^main/$', 'common.views.index', name='index'),
    url(r'^', include('django.contrib.staticfiles.urls')),
)

urlpatterns += staticfiles_urlpatterns()

pim/apps/common/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib import admin
import consts as CONST


#class Living_situation(models.Model):
#    """
#    暮らし状況
#    """
#    def __unicode__(self):
#        return self.living_situation
    # 暮らし状況
#    living_situation = models.CharField(max_length=200)

#    def encode(self):
#        return {
#                'living_situation': self.living_situation,
#                }

#class Type(models.Model):
#    """
#    性格
#    """
#    def __unicode__(self):
#        return self.type
#    # 性格
#    type = models.CharField(max_length=200)

#    def encode(self):
#        return {
#                'type': self.type,
#                }

#class Level(models.Model):
#    """
#    レベル
#    """
#    def __unicode__(self):
#        return self.level_description
#    # レベル説明
#    level_description = models.CharField(max_length=50)

#    def encode(self):
#        return {
#                'level_description': self.level_description,
#                }

class Target(models.Model):
    """
    ターゲット情報モデル
    """
    def __unicode__(self):
        return self.name
    # 名前（漢字）
    name = models.CharField(max_length=200)
    # よみかた）
    reading = models.CharField(max_length=200)
    # 呼び名
    nick_name = models.CharField(max_length=200, blank=True)
    # 難易度
    difficulty = models.CharField(max_length=200, blank=True, null=True, choices=CONST.DIFFICULTY_CHOICES)
    #レベル
    level = models.IntegerField(choices=CONST.LEVEL_CHOICES)
    # 接触の目的
    purpose = models.CharField(max_length=50)
    # 会った日
    met_date = models.DateField()
    # 会った場所
    met_place = models.CharField(max_length=50, blank=True)
    # 会ったシチュエーション
    met_situation = models.CharField(max_length=200, blank=True)
    # 誕生日
    birthday = models.DateField(blank=True, null=True)
    # 電話番号
    phone_number = models.CharField(max_length=11, blank=True, null=True)
    # メールアドレス
    mail = models.CharField(max_length=200, blank=True)
    # 住所
    address = models.CharField(max_length=200, blank=True)
    # 職業
    occupation = models.CharField(max_length=200, blank=True)
    # 会社
    company = models.CharField(max_length=200, blank=True)
    # 趣味
    hobby = models.CharField(max_length=200, blank=True)
    # 出身地
    birth_place = models.CharField(max_length=200, blank=True)
    # ひとり暮らし:1, 実家:2, ルームシェア:3
    living_situation = models.CharField(max_length=200, blank=True, null=True, choices=CONST.LIVING_SITUATION_CHOICES)
    # 備考
    remarks = models.TextField(blank=True)
    # 性格1
    type_1 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 性格2
    type_2 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 性格3
    type_3 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES)
    # 担当者ありフラグ
    taken_flg = models.BooleanField(default=False)
    # 終了フラグ
    done_flg = models.BooleanField(default=False)
    # ターゲット画像
    target_photo = models.ImageField(upload_to='targetPhoto/', null=True, blank=True)

    def encode(self):
        return {
                'name': self.name,
                'reading': self.reading,
                'difficulty': self.difficulty,
                'level': self.level,
                'purpose': self.purpose,
                'met_date': self.met_date,
                'met_place': self.met_place,
                'met_situation': self.met_situation,
                'birthday': self.birthday,
                'phone_number': self.phone_number,
                'mail': self.mail,
                'address': self.address,
                'occupation': self.occupation,
                'company': self.company,
                'hobby': self.hobby,
                'birth_place': self.birth_place,
                'living_situation': self.living_situation,
                'remarks': self.remarks,
                'type_1': self.type_1,
                'type_2': self.type_2,
                'type_3': self.type_3,
                'done_flg': self.done_flg,
                }

class Introduce(models.Model):
    """
    紹介者管理
    """
    def __unicode__(self):
        return self.introduced_by
    #紹介された人
    target = models.ForeignKey(Target, related_name='target')
    #紹介者
    introduced_by = models.ForeignKey(Target, related_name='introduced_by')

    def encode(self):
        return {
                'target': self.target.encode(),
                'introduced_by': self.introduced_by.encode(),
                }

class Target_relationship(models.Model):
    """
    ターゲット同士の関係性
    """
    def __unicode__(self):
        return self.relationship
    #ターゲット1
    target1 = models.ForeignKey(Target, related_name='target1')
    #ターゲット2
    target2 = models.ForeignKey(Target, related_name='target2')
    #関係性
    relationship = models.CharField(max_length=200)

    def encode(self):
        return {
                'target1': self.target1.encode(),
                'target2': self.target2.encode(),
                'relationship': self.relationship,
                }

class Team(models.Model):
    """
    チームモデル
    """
    def __unicode__(self):
        return self.name
    # チーム名
    name = models.CharField(max_length=200)
    # メンバー上限
    team_size = models.IntegerField(default=5)

    def encode(self):
        return {
                'name': self.name,
                }

class CustomUserManager(models.Manager):
    def create_user(self, username, email):
        return self.model._default_manager.create(username=username)

class User (models.Model):
    """
    ユーザモデル
    """
    def __unicode__(self):
        return self.username
    # ユーザID
    username = models.CharField(max_length=20, primary_key=True)
    # 名前（漢字）
    name = models.CharField(max_length=200, blank=True, verbose_name='名前(漢字)')
    # 名前（ひらがな）
    name_hiragana = models.CharField(max_length=200, blank=True, verbose_name='名前(ひらがな)')
    # 名前（英語）
    name_en = models.CharField(max_length=200, blank=True, verbose_name='名前(英語)')
    # チーム
    team = models.ForeignKey(Team, blank=True, null=True, verbose_name='チーム')
    # 誕生日
    birthday = models.DateField(blank=True, null=True, verbose_name='誕生日')
    # 出身地
    birth_place = models.CharField(max_length=200, blank=True, verbose_name='出身地')
    # 対象性格1
    target_type_1 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格1')
    # 対象性格2
    target_type_2 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格2')
    # 対象性格3
    target_type_3 = models.CharField(max_length=200, blank=True, null=True, choices=CONST.TYPE_CHOICES, verbose_name='対象性格3')
    # email
    email = models.CharField(max_length=200, verbose_name='Email')
    # プロファイル画像
    profile_photo = models.URLField(max_length=200, blank=True)
    # is_active
    is_active  = models.BooleanField(default=True)
    # last login
    last_login = models.DateTimeField(blank=True, null=True)
    #チーム管理者フラグ
#    team_admin_flg = models.BooleanField(default=False)
    # ユーザの状態。0=アカウント停止、1=仮登録、2=無料会員、3=有料会員
    status = models.IntegerField(default=1)

    objects = CustomUserManager();

    def is_authenticated(self):
        return True

    def encode(self):
        return {
                'username': self.username,
                'name': self.name,
                'name_hiragana': self.name_hiragana,
                'name_en': self.name_en,
                'team': self.team,
                'birthday': self.birthday,
                'birth_place': self.birth_place,
                'target_type_1': self.target_type_1,
                'target_type_2': self.target_type_2,
                'target_type_3': self.target_type_3,
                'profile_photo': self.profile_photo,
                }

class Membership(models.Model):
    """
    チームとメンバーの関係の中間モデル
    """
    def __unicode__(self):
        return self.team.name

    # チーム
    team = models.ForeignKey(Team)
    # ユーザ
    user = models.ForeignKey(User)
    # チーム管理者フラグ
    team_admin_flg = models.BooleanField(default=False)

    def encode(self):
        return {
                'team': self.team.encode(),
                'user': self.ruser.encode(),
                'team_admin_flg': self.team_admin_flg.encode(),
                }


class Invitation(models.Model):
    """
    チーム招待中間モデル
    """
    def __unicode__(self):
        return self.team

    # チーム
    team = models.ForeignKey(Team)
    # 被招待者
    invited_user = models.ForeignKey(User, related_name="invited_user")
    # 招待者
    invited_by = models.ForeignKey(User, related_name="invited_by")
    # 管理者承認フラグ
    approve_by_admin_flg = models.BooleanField(default=False)
    # 被招待者承認フラグ
    approve_by_user_flg = models.BooleanField(default=False)

#class Progress(models.Model):
#    """
#    進捗マスタ
#    """
#    def __unicode__(self):
#        return self.progress_name
#    #進捗名
#    progress_name = models.CharField(max_length=50)

#    def encode(self):
#        return {
#                'progress_name': self.progress_name,
#                }

class Progress_management(models.Model):
    """
    担当者定義モデル
    """
    def __unicode__(self):
        return unicode(self.progress)
    # 顧客
    target = models.ForeignKey(Target, verbose_name='顧客')
    # 担当者
    responsible_by = models.ForeignKey(User, verbose_name='担当者')
    # 関係性
    relationship = models.CharField(max_length=200, verbose_name='関係性')
    # 進捗状況
    progress = models.CharField(max_length=200, choices=CONST.PROGRESS_CHOICES, verbose_name='進捗状況')
    # 備考
    remarks = models.TextField(blank=True, verbose_name='備考')
    # 登録日時
    registered_at = models.DateTimeField(auto_now_add=True, verbose_name='登録日時')

    def encode(self):
        return {
                'target': self.target.encode(),
                'responsible_by': self.responsible_by.encode(),
                'relationship': self.relationship,
                'progress': self.progress,

pim/apps/target_list/forms.py
'''
Created on 2014/07/23

@author: h-nagata
'''
from django.db import models
from django.forms import ModelForm
import common.models as MODELS

class TargetForm(ModelForm):
    class Meta:
        model = MODELS.Target
        
    def __init__(self, *args, **kwargs):
        super(TargetForm, self).__init__(*args, **kwargs)

        self.fields['name_kanji'].required = False
        self.fields['name_hiragana'].required = False
        self.fields['nick_name'].required = False
        self.fields['difficulty'].required = False
        self.fields['level'].required = False
        self.fields['purpose'].required = False
        self.fields['met_place'].required = False
        self.fields['met_situation'].required = False
        self.fields['birthday'].required = False
        self.fields['phone_number'].required = False
        self.fields['mail'].required = False
        self.fields['address'].required = False
        self.fields['occupation'].required = False
        self.fields['company'].required = False
        self.fields['hobby'].required = False
        self.fields['birth_place'].required = False
        self.fields['living_situation'].required = False
        self.fields['remarks'].required = False
        self.fields['type_1'].required = False
        self.fields['type_2'].required = False
        self.fields['type_3'].required = False
        self.fields['done_flg'].required = False
        self.fields['profile_photo'].required = False
        

pim/apps/target_list/views.py
# -*- coding: utf-8 -*-
# targetlist views
from django.shortcuts import render
from django.core.context_processors import csrf
import configs as CONFIG
import forms as FORMS
import services as SERVICES
import messages as MSGS
import logging

logger = logging.getLogger('app')

def index(request):
    """
    ターゲット一覧画面インデックス
    最初に必ず通る
    """
    logger.info('ターゲットリスト画面開始')
    forms = {'addForm':FORMS.TargetForm()}
    c = {}    
    c.update(forms)
    return show(request, c)

def add(request):
    """
    ターゲット登録
    """
    logger.info('ターゲット登録')

    if request.method == 'POST':
        addTargetForm = FORMS.TargetForm(request.POST)
        result = SERVICES.addNewTarget(addTargetForm, request.user)

        if not result == 'success':
            fail_form = FORMS.TargetForm(request.POST)
            c = {'addForm':fail_form}
            c.update({'form_message':MSGS.ADD_FAIL})

            return show(request, c)

    c = {'form_message': MSGS.ADD_SUCCESS}
    c.update({'addForm':FORMS.TargetForm()})
    return show(request, c)

def show(request, c):
    """
    ターゲット一覧表示メソッド
    URLなど必要な値をセットし、表示する
    """
    logger.info('ターゲットリスト表示')
    
    target_list = SERVICES.getAllTargetList()
    c.update({'target_list':target_list})

    main_url = CONFIG.TOP_URL
    page_title = CONFIG.TARGET_LIST_PAGE_TITLE_URL
    main_content = CONFIG.TARGET_LIST_MAIN_URL
    sub_content = CONFIG.TARGET_LIST_SUB_URL

    url_dict = {'main_url':main_url, 
                'page_title':page_title, 
                'main_content':main_content,
                'sub_content':sub_content}
    c.update(csrf(request))
    c.update(url_dict)
    c.update(CONFIG.ACTION_DICT)
    return render(request, 'common/main.html', c)
    

pim/templates/target_list/main_content.html
    <div id="main_content">
        <table class="table table-hover">
          <tbody>
            {% for target in target_list%}
            <tr>
              <td class="col-md-2">
                <img src="{{STATIC_URL}}images/no_image.png" width="100%">
              </td>
              <td class="col-md-10">
                <table style="width:100%;">
                  <tr>
                    <td class="col-md-12" colspan="4">
                      {{ target.name_kanji}} : {{ target.name_en }} {%if target.nick_name %}({{ target.nick_name }}){% endif %}
                    </td>
                  <tr>
                  <tr>
                    <th class="col-md-2">
                      職業:
                    </th>
                    <td class="col-md-5">
                      {% if target.occupation  %}
                      {{ target.occupation }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                    <th class="col-md-2">
                      誕生日:
                    </th>
                    <td class="col-md-5">
                      {% if target.birthday  %}
                      {{ target.birthday }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      <span style="font-size:13px;">電話番号:</span>
                    </th>
                    <td class="col-md-5">
                      {% if target.phone_number  %}
                      {{ target.phone_number }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                    <th class="col-md-2">
                      メール
                    </th>
                    <td class="col-md-5">
                      {% if target.mail  %}
                      {{ target.mail }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      住所:
                    </th>
                    <td class="col-md-5">
                      {% if target.address  %}
                      {{ target.address }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                    <th class="col-md-2">
                      状況:
                    </th>
                    <td class="col-md-5">
                      {% if target.living_situation  %}
                      {{ target.living_situation }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      <span style="font-size:13px;">きっかけ:</span>
                    </th>
                    <td class="col-md-5">
                      {% if target.met_situation  %}
                      {{ target.met_situation }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                    <th class="col-md-2">
                      趣味:
                    </th>
                    <td class="col-md-5">
                      {% if target.hobby  %}
                      {{ target.hobby }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      性格:
                    </th>
                    <td class="col-md-10" colspan="3">
                      {% if target.type_1  %}
                      {{ target.type_1 }}
                      {% endif %}
                      {% if target.type_2  %}
                      {{ target.type_2 }}
                      {% endif %}
                      {% if target.type_3  %}
                      {{ target.type_3 }}
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      目的:
                    </th>
                    <td class="col-md-5">
                      {% if target.purpose  %}
                      {{ target.purpose }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                    <th class="col-md-2">
                      接触日:
                    </th>
                    <td class="col-md-5">
                      {% if target.met_date  %}
                      {{ target.met_date }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                  <tr>
                    <th class="col-md-2">
                      level:
                    </th>
                    <td class="col-md-5">
                      1
                    </td>
                    <th class="col-md-2">
                      難易度:
                    </th>
                    <td class="col-md-5">
                      {% if target.difficulty %}
                      {{ target.difficulty }}
                      {% else %}
                      &nbsp;-
                      {% endif %}
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>
    </div>

pim/templates/target_list/page_title.html
<div class="page_title"><h3>target list</h3></div>

pim/templates/target_list/sub_content.html
    <div id="sub_content">
        {{form_message}}
        <form method="POST" action="{{main_url}}">
        {%csrf_token%}

        <div class="fieldWrapper">
          {{ addForm.name_kanji.errors }}
          <label for="id_name_kanji">名前(漢字):</label>
          {{ addForm.name_kanji }}
        </div>
        <div class="fieldWrapper">
          {{ addForm.name_hiragana.errors }}
          <label for="id_name_hiragana">よみかた:</label>
          {{ addForm.name_hiragana }}
        </div>
        <div class="fieldWrapper">
          {{ addForm.name_en.errors }}
          <label for="id_name_en">名前(英語):</label>
          {{ addForm.name_en }}
        </div>
        <div class="fieldWrapper">
          {{ addForm.met_date.errors }}
          <label for="id_met_date">会った日:</label>
          {{ addForm.met_date }}
        </div>
        <a href="#" onclick="display('target_detail_inputs');">詳細入力</a>
        
        <!-- 以下詳細登録とする。ボタン押したらニュって出てくる感じ-->
        <div id="target_detail_inputs" style="display:none;">
	        <div class="fieldWrapper">
	          {{ addForm.nick_name.errors }}
	          <label for="id_nick_name">ニックネーム:</label>
	          {{ addForm.nick_name }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.difficulty.errors }}
	          <label for="id_difficulty">難易度:</label>
	          {{ addForm.difficulty }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.level.errors }}
	          <label for="id_level">レベル:</label>
	          {{ addForm.level }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.purpose.errors }}
	          <label for="id_purpose">目的:</label>
	          {{ addForm.purpose }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.met_place.errors }}
	          <label for="id_met_place">場所:</label>
	          {{ addForm.met_place }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.met_situation.errors }}
	          <label for="id_met_situation">きっかけ:</label>
	          {{ addForm.met_situation }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.birthday.errors }}
	          <label for="id_birthday">誕生日:</label>
	          {{ addForm.birthday }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.phone_number.errors }}
	          <label for="id_phone_number">電話番号:</label>
	          {{ addForm.phone_number }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.mail.errors }}
	          <label for="id_mail">メール:</label>
	          {{ addForm.mail }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.address.errors }}
	          <label for="id_address">住所:</label>
	          {{ addForm.address }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.occupation.errors }}
	          <label for="id_occupation">職業:</label>
	          {{ addForm.occupation }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.company.errors }}
	          <label for="id_company">会社:</label>
	          {{ addForm.company }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.hobbu.errors }}
	          <label for="id_hobby">趣味:</label>
	          {{ addForm.hobby }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.birth_place.errors }}
	          <label for="id_birth_place">出身地:</label>
	          {{ addForm.birth_place }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.living_situation.errors }}
	          <label for="id_living_situation">暮らし方:</label>
	          {{ addForm.living_situation }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.remarks.errors }}
	          <label for="id_remarks">備考:</label>
	          {{ addForm.remarks }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.type_1.errors }}
	          <label for="id_type_1">性格1:</label>
	          {{ addForm.type_1 }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.type_2.errors }}
	          <label for="id_type_2">性格2:</label>
	          {{ addForm.type_2 }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.type_3.errors }}
	          <label for="id_type_3">性格3:</label>
	          {{ addForm.type_3 }}
	        </div>
	        <div class="fieldWrapper">
	          {{ addForm.profile_photo.errors }}
	          <label for="id_profile_photo">写真:</label>
	          {{ addForm.profile_photo }}
	        </div>
        </div>

        <input type="hidden" name="action" value="{{ACTION_TARGET_ADD}}">
        <input type="submit" value="登録"/>
      </form>
      
    </div>
    